Feature: Added primitive CQRS and InMemoryRepository
micro-shoppy/catalog pull request #2
Opened 2021-08-25 19:59 UTC by RafKulas

Closes #1

2021-08-25 20:32 UTC, krzysztofzajaczkowski requested changes

2021-08-25 20:32 UTC, krzysztofzajaczkowski commented on Microshoppy.Catalog/Microshoppy.Catalog/src/CQRS/Handler.cs
> +	public class Handler
Handler doesn't do anything on its own. It should be marked as abstract

2021-08-25 20:32 UTC, krzysztofzajaczkowski commented on Microshoppy.Catalog/Microshoppy.Catalog/src/Repositories/ICatalogRepository.cs
> +		void DeleteProduct(Guid productId);
All repository methods should be asynchronous.

2021-08-26 06:13 UTC, closed without merging

2021-08-26 06:13 UTC, RafKulas commented
wrong main branch